title: Streamdata Gallery
url: aws-elastic-load-balancing.api.streamdata.gallery
tag: AWS Elastic Load Balancing
markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]
github_user: streamdata-gallery-organizations
github_repo: aws-elastic-load-balancing
github_branch: master
collections:
  listings:
    output: true
    permalink: /listings/:path/
defaults:
  - scope:
      type: listings
    values:
      layout: listings
